// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHRvYTM7weKV8MhiBcEQ16LNH6Hd0Csq8',
    appId: '1:202403125129:android:feae8423682b0b9c37b358',
    messagingSenderId: '202403125129',
    projectId: 'crickflow-b06bc',
    storageBucket: 'crickflow-b06bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBem5ugk3fGc7HiaHO9pCbqxt43fCuoe7Q',
    appId: '1:202403125129:ios:031dba2e4db98d7237b358',
    messagingSenderId: '202403125129',
    projectId: 'crickflow-b06bc',
    storageBucket: 'crickflow-b06bc.firebasestorage.app',
    androidClientId: '202403125129-i25q82hre5c1ejeu26gtbkertv4bts8i.apps.googleusercontent.com',
    iosClientId: '202403125129-710maflgfdh2hgdbuh6hqq2hfddr0m6f.apps.googleusercontent.com',
    iosBundleId: 'com.mavixas.crickflow',
  );

}