import '../../core/constants/enums.dart';
import '../../data/models/ball_event_model.dart';
import '../../data/models/match_model.dart';
import '../../data/models/player_model.dart';
import 'player_badge_progression_service.dart';
import 'player_cricket_profile_models.dart';

class PlayerBadgeCatalogService {
  const PlayerBadgeCatalogService({
    this.progressionService = const PlayerBadgeProgressionService(),
  });

  final PlayerBadgeProgressionService progressionService;

  static const catalog = <PlayerBadgeDefinition>[
    // Batting â€” match
    PlayerBadgeDefinition(
      id: 'bat_30',
      title: '30 in a Match',
      category: BadgeType.batting,
      tier: BadgeTier.bronze,
      requirement: 'Score 30+ runs in a match',
      progressionGroup: PlayerBadgeProgressionService.runsInMatchGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'bat_50',
      title: '50 in a Match',
      category: BadgeType.batting,
      tier: BadgeTier.silver,
      requirement: 'Score 50+ runs in a match',
      progressionGroup: PlayerBadgeProgressionService.runsInMatchGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'bat_75',
      title: '75 in a Match',
      category: BadgeType.batting,
      tier: BadgeTier.silver,
      requirement: 'Score 75+ runs in a match',
      progressionGroup: PlayerBadgeProgressionService.runsInMatchGroup,
      groupOrder: 3,
    ),
    PlayerBadgeDefinition(
      id: 'bat_100',
      title: '100 in a Match',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: 'Score 100+ runs in a match',
      progressionGroup: PlayerBadgeProgressionService.runsInMatchGroup,
      groupOrder: 4,
    ),
    PlayerBadgeDefinition(
      id: 'bat_150',
      title: '150 in a Match',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: 'Score 150+ runs in a match',
      progressionGroup: PlayerBadgeProgressionService.runsInMatchGroup,
      groupOrder: 5,
    ),
    PlayerBadgeDefinition(
      id: 'bat_200',
      title: '200 in a Match',
      category: BadgeType.batting,
      tier: BadgeTier.diamond,
      requirement: 'Score 200+ runs in a match',
      progressionGroup: PlayerBadgeProgressionService.runsInMatchGroup,
      groupOrder: 6,
    ),
    PlayerBadgeDefinition(
      id: 'fast_50',
      title: 'Fast Fifty',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: 'Fifty in 30 balls or fewer',
    ),
    PlayerBadgeDefinition(
      id: 'fast_100',
      title: 'Fast Century',
      category: BadgeType.batting,
      tier: BadgeTier.diamond,
      requirement: 'Century in 50 balls or fewer',
    ),
    PlayerBadgeDefinition(
      id: 'sr_200',
      title: '200+ SR Match',
      category: BadgeType.batting,
      tier: BadgeTier.silver,
      requirement: 'Strike rate 200+ (6+ balls or 21+ runs)',
      progressionGroup: PlayerBadgeProgressionService.strikeRateGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'sr_250',
      title: '250+ SR Match',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: 'Strike rate 250+ (6+ balls or 21+ runs)',
      progressionGroup: PlayerBadgeProgressionService.strikeRateGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'sr_300',
      title: '300+ SR Match',
      category: BadgeType.batting,
      tier: BadgeTier.diamond,
      requirement: 'Strike rate 300+ (6+ balls or 21+ runs)',
      progressionGroup: PlayerBadgeProgressionService.strikeRateGroup,
      groupOrder: 3,
    ),
    PlayerBadgeDefinition(
      id: '4s_10',
      title: '10 Fours Match',
      category: BadgeType.batting,
      tier: BadgeTier.bronze,
      requirement: 'Hit 10+ fours in a match',
    ),
    PlayerBadgeDefinition(
      id: '4s_15',
      title: '15 Fours Match',
      category: BadgeType.batting,
      tier: BadgeTier.silver,
      requirement: 'Hit 15+ fours in a match',
    ),
    PlayerBadgeDefinition(
      id: '4s_20',
      title: '20 Fours Match',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: 'Hit 20+ fours in a match',
    ),
    PlayerBadgeDefinition(
      id: '6s_5',
      title: '5 Sixes Match',
      category: BadgeType.batting,
      tier: BadgeTier.bronze,
      requirement: 'Hit 5+ sixes in a match',
    ),
    PlayerBadgeDefinition(
      id: '6s_10',
      title: '10 Sixes Match',
      category: BadgeType.batting,
      tier: BadgeTier.silver,
      requirement: 'Hit 10+ sixes in a match',
    ),
    PlayerBadgeDefinition(
      id: '6s_15',
      title: '15 Sixes Match',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: 'Hit 15+ sixes in a match',
    ),
    // Batting — career (one-time)
    PlayerBadgeDefinition(
      id: 'career_runs_100',
      title: '100 Runs Career',
      category: BadgeType.batting,
      tier: BadgeTier.bronze,
      requirement: '100 career runs',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerRunsGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'career_runs_500',
      title: '500 Runs Career',
      category: BadgeType.batting,
      tier: BadgeTier.silver,
      requirement: '500 career runs',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerRunsGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'career_runs_1000',
      title: '1000 Runs Career',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: '1000 career runs',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerRunsGroup,
      groupOrder: 3,
    ),
    PlayerBadgeDefinition(
      id: 'career_runs_5000',
      title: '5000 Runs Career',
      category: BadgeType.batting,
      tier: BadgeTier.diamond,
      requirement: '5000 career runs',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerRunsGroup,
      groupOrder: 4,
    ),
    PlayerBadgeDefinition(
      id: 'career_runs_10000',
      title: '10000 Runs Career',
      category: BadgeType.batting,
      tier: BadgeTier.diamond,
      requirement: '10000 career runs',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerRunsGroup,
      groupOrder: 5,
    ),
    PlayerBadgeDefinition(
      id: 'career_6s_50',
      title: '50 Sixes',
      category: BadgeType.batting,
      tier: BadgeTier.bronze,
      requirement: '50 career sixes',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerSixesGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'career_6s_100',
      title: '100 Sixes',
      category: BadgeType.batting,
      tier: BadgeTier.silver,
      requirement: '100 career sixes',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerSixesGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'career_6s_250',
      title: '250 Sixes',
      category: BadgeType.batting,
      tier: BadgeTier.gold,
      requirement: '250 career sixes',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerSixesGroup,
      groupOrder: 3,
    ),
    PlayerBadgeDefinition(
      id: 'career_6s_500',
      title: '500 Sixes',
      category: BadgeType.batting,
      tier: BadgeTier.diamond,
      requirement: '500 career sixes',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerSixesGroup,
      groupOrder: 4,
    ),
    // Bowling â€” match
    PlayerBadgeDefinition(
      id: 'bowl_3',
      title: '3 Wicket Haul',
      category: BadgeType.bowling,
      tier: BadgeTier.bronze,
      requirement: 'Take 3+ wickets in a match',
    ),
    PlayerBadgeDefinition(
      id: 'bowl_4',
      title: '4 Wicket Haul',
      category: BadgeType.bowling,
      tier: BadgeTier.silver,
      requirement: 'Take 4+ wickets in a match',
    ),
    PlayerBadgeDefinition(
      id: 'bowl_5',
      title: '5 Wicket Haul',
      category: BadgeType.bowling,
      tier: BadgeTier.gold,
      requirement: 'Take 5+ wickets in a match',
    ),
    PlayerBadgeDefinition(
      id: 'bowl_6',
      title: '6 Wicket Haul',
      category: BadgeType.bowling,
      tier: BadgeTier.diamond,
      requirement: 'Take 6+ wickets in a match',
    ),
    PlayerBadgeDefinition(
      id: 'maiden',
      title: 'Maiden Over',
      category: BadgeType.bowling,
      tier: BadgeTier.silver,
      requirement: 'Bowl a maiden over',
    ),
    // Bowling — career (one-time)
    PlayerBadgeDefinition(
      id: 'career_wkts_50',
      title: '50 Wickets Career',
      category: BadgeType.bowling,
      tier: BadgeTier.silver,
      requirement: '50 career wickets',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerWicketsGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'career_wkts_100',
      title: '100 Wickets Career',
      category: BadgeType.bowling,
      tier: BadgeTier.gold,
      requirement: '100 career wickets',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerWicketsGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'career_wkts_250',
      title: '250 Wickets Career',
      category: BadgeType.bowling,
      tier: BadgeTier.diamond,
      requirement: '250 career wickets',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerWicketsGroup,
      groupOrder: 3,
    ),
    PlayerBadgeDefinition(
      id: 'career_wkts_500',
      title: '500 Wickets Career',
      category: BadgeType.bowling,
      tier: BadgeTier.diamond,
      requirement: '500 career wickets',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerWicketsGroup,
      groupOrder: 4,
    ),
    PlayerBadgeDefinition(
      id: 'econ_4',
      title: 'Economy Under 4',
      category: BadgeType.bowling,
      tier: BadgeTier.gold,
      requirement: 'Career economy below 4 (20+ overs)',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'econ_3',
      title: 'Economy Under 3',
      category: BadgeType.bowling,
      tier: BadgeTier.diamond,
      requirement: 'Career economy below 3 (20+ overs)',
      repeatability: BadgeRepeatability.oneTime,
    ),
    // Fielding
    PlayerBadgeDefinition(
      id: 'catch_3',
      title: '3 Catches Match',
      category: BadgeType.fielding,
      tier: BadgeTier.bronze,
      requirement: '3+ catches in a match',
    ),
    PlayerBadgeDefinition(
      id: 'catch_5',
      title: '5 Catches Match',
      category: BadgeType.fielding,
      tier: BadgeTier.gold,
      requirement: '5+ catches in a match',
    ),
    PlayerBadgeDefinition(
      id: 'ro_direct',
      title: 'Direct Hit Run Out',
      category: BadgeType.fielding,
      tier: BadgeTier.silver,
      requirement: 'Direct hit run out in a match',
    ),
    PlayerBadgeDefinition(
      id: 'ro_2',
      title: '2 Run Outs Match',
      category: BadgeType.fielding,
      tier: BadgeTier.gold,
      requirement: '2+ run outs in a match',
    ),
    PlayerBadgeDefinition(
      id: 'safe_hands',
      title: 'Safe Hands',
      category: BadgeType.fielding,
      tier: BadgeTier.silver,
      requirement: '5+ dismissals in a match',
    ),
    PlayerBadgeDefinition(
      id: 'career_catch_50',
      title: '50 Catches',
      category: BadgeType.fielding,
      tier: BadgeTier.bronze,
      requirement: '50 career catches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerCatchesGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'career_catch_100',
      title: '100 Catches',
      category: BadgeType.fielding,
      tier: BadgeTier.gold,
      requirement: '100 career catches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerCatchesGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'career_catch_250',
      title: '250 Catches',
      category: BadgeType.fielding,
      tier: BadgeTier.diamond,
      requirement: '250 career catches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.careerCatchesGroup,
      groupOrder: 3,
    ),
    // Captaincy
    PlayerBadgeDefinition(
      id: 'cap_wins_10',
      title: '10 Wins',
      category: BadgeType.captaincy,
      tier: BadgeTier.bronze,
      requirement: '10 wins as captain',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.captainWinsGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'cap_wins_25',
      title: '25 Wins',
      category: BadgeType.captaincy,
      tier: BadgeTier.silver,
      requirement: '25 wins as captain',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.captainWinsGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'cap_wins_50',
      title: '50 Wins',
      category: BadgeType.captaincy,
      tier: BadgeTier.gold,
      requirement: '50 wins as captain',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.captainWinsGroup,
      groupOrder: 3,
    ),
    PlayerBadgeDefinition(
      id: 'cap_wins_100',
      title: '100 Wins',
      category: BadgeType.captaincy,
      tier: BadgeTier.diamond,
      requirement: '100 wins as captain',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.captainWinsGroup,
      groupOrder: 4,
    ),
    PlayerBadgeDefinition(
      id: 'winning_machine',
      title: 'Winning Machine',
      category: BadgeType.captaincy,
      tier: BadgeTier.gold,
      requirement: '70%+ win rate as captain (10+ matches)',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'chase_master',
      title: 'Successful Chase Master',
      category: BadgeType.captaincy,
      tier: BadgeTier.silver,
      requirement: '5+ successful chases as captain',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'defender',
      title: 'Defender',
      category: BadgeType.captaincy,
      tier: BadgeTier.silver,
      requirement: 'Defend a target of 100+ as captain',
      repeatability: BadgeRepeatability.oneTime,
    ),
    // Career (one-time)
    PlayerBadgeDefinition(
      id: 'debut',
      title: 'Debut Match',
      category: BadgeType.career,
      tier: BadgeTier.bronze,
      requirement: 'Play your first match',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.matchesPlayedGroup,
      groupOrder: 1,
    ),
    PlayerBadgeDefinition(
      id: 'matches_25',
      title: '25 Matches',
      category: BadgeType.career,
      tier: BadgeTier.bronze,
      requirement: 'Play 25 matches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.matchesPlayedGroup,
      groupOrder: 2,
    ),
    PlayerBadgeDefinition(
      id: 'matches_50',
      title: '50 Matches',
      category: BadgeType.career,
      tier: BadgeTier.silver,
      requirement: 'Play 50 matches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.matchesPlayedGroup,
      groupOrder: 3,
    ),
    PlayerBadgeDefinition(
      id: 'matches_100',
      title: '100 Matches',
      category: BadgeType.career,
      tier: BadgeTier.gold,
      requirement: 'Play 100 matches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.matchesPlayedGroup,
      groupOrder: 4,
    ),
    PlayerBadgeDefinition(
      id: 'matches_250',
      title: '250 Matches',
      category: BadgeType.career,
      tier: BadgeTier.gold,
      requirement: 'Play 250 matches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.matchesPlayedGroup,
      groupOrder: 5,
    ),
    PlayerBadgeDefinition(
      id: 'matches_500',
      title: '500 Matches',
      category: BadgeType.career,
      tier: BadgeTier.diamond,
      requirement: 'Play 500 matches',
      repeatability: BadgeRepeatability.oneTime,
      progressionGroup: PlayerBadgeProgressionService.matchesPlayedGroup,
      groupOrder: 6,
    ),
    PlayerBadgeDefinition(
      id: 'veteran',
      title: 'Veteran',
      category: BadgeType.career,
      tier: BadgeTier.gold,
      requirement: 'Play 200+ matches',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'legend',
      title: 'Legend',
      category: BadgeType.career,
      tier: BadgeTier.diamond,
      requirement: 'Play 1000+ matches',
      repeatability: BadgeRepeatability.oneTime,
    ),
    // Special — repeatable match achievements
    PlayerBadgeDefinition(
      id: 'all_round_match',
      title: 'Century + 5 Wickets Same Match',
      category: BadgeType.special,
      tier: BadgeTier.diamond,
      requirement: '100+ runs and 5+ wickets in same match',
    ),
    PlayerBadgeDefinition(
      id: 'potm_streak',
      title: 'Player Of Match Streak',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: '2 consecutive Player Of Match awards',
    ),
    PlayerBadgeDefinition(
      id: 'all_round_hero',
      title: 'All Round Hero',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: '50+ runs and 3+ wickets in same match',
    ),
    PlayerBadgeDefinition(
      id: 'iron_man',
      title: 'Iron Man',
      category: BadgeType.special,
      tier: BadgeTier.silver,
      requirement: 'Play 10 matches in 30 days',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'finisher',
      title: 'Finisher',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: '30+ runs at SR 150+ batting second',
    ),
    PlayerBadgeDefinition(
      id: 'super_over_hero',
      title: 'Super Over Hero',
      category: BadgeType.special,
      tier: BadgeTier.diamond,
      requirement: 'Top scorer in a super over match',
    ),
    // Special — one-time first achievements
    PlayerBadgeDefinition(
      id: 'first_century',
      title: 'First Century',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: 'Score your first 100 in a match',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'first_five_wicket',
      title: 'First Five Wicket Haul',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: 'Take your first 5 wickets in a match',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'first_hat_trick',
      title: 'First Hat-trick',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: 'Take your first hat-trick',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'first_motm',
      title: 'First Man of the Match',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: 'First Player of the Match award',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'first_mvp_rank',
      title: 'First MVP #1 Rank',
      category: BadgeType.special,
      tier: BadgeTier.diamond,
      requirement: 'Reach #1 on the MVP leaderboard',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'tournament_winner',
      title: 'Tournament Winner',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: 'Win a tournament match',
      repeatability: BadgeRepeatability.oneTime,
    ),
    PlayerBadgeDefinition(
      id: 'captain_champion',
      title: 'Captain Champion',
      category: BadgeType.special,
      tier: BadgeTier.gold,
      requirement: 'Win a tournament match as captain',
      repeatability: BadgeRepeatability.oneTime,
    ),
  ];

  List<PlayerBadgeProgress> evaluate({
    required PlayerModel player,
    required List<MatchModel> completedMatches,
    CaptainStatsSnapshot captainStats = CaptainStatsSnapshot.empty,
    Map<String, List<BallEventModel>> ballEventsByMatch = const {},
  }) {
    final records = progressionService.computeRecords(
      playerId: player.id,
      stats: player.stats,
      completedMatches: completedMatches,
      captainStats: captainStats,
      ballEventsByMatch: ballEventsByMatch,
      catalog: catalog,
    );
    return progressionService.toProgressList(
      catalog: catalog,
      records: records,
      playerId: player.id,
      stats: player.stats,
      completedMatches: completedMatches,
      captainStats: captainStats,
      ballEventsByMatch: ballEventsByMatch,
    );
  }
}

